version: '3.7'

services:
  
  webs:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - './web:/usr/src/app'
    #   - '/app/node_modules'
    ports:
      - 3002:3000
